version: '3.9'

services:
  todo-front:
    container_name: todo-front
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - .env.production
    volumes:
    - ../:/app
    ports:
    - 3000:3000
    networks: 
      - mytodo

networks:
  mytodo:
    external:
      name: mytodo